image: node:16.11.1-buster

clone:
  depth: full

definitions:
  services:
    docker:
      memory: 3072
  steps:
    - step: &test
        name: Test
        script:
          - npm ci
          - npm run lint
          - npm run test

    - step: &release
        name: Publish 
        script:
          - git fetch
          - git checkout main
          - VERSION=$(echo $BITBUCKET_TAG | sed 's/^.*[A-Za-z]-//g')
          - npm version $VERSION --allow-same-version
          - npm ci
          - git config --global user.name "Automated NPM Release"
          - git config --global user.email "devops+npm-deploy@aligent.com.au"
          - git push origin main
          - git tag -f -m 'Version ${VERSION}' -a version-${VERSION}
          - git push --delete origin release-${VERSION}
          - git push --tags

    - step: &publish
        name: Publish 
        script:
          - npm run build
          - pipe: atlassian/npm-publish:0.3.3
            variables:
              NPM_TOKEN: $NPM_TOKEN

pipelines:
  pull-requests:
    "**":
      - step: *test
  tags:
    release-*:
      - step: *release
    version-*:
      - step: *publish
