export const PACKAGE_JSON = {
    author: 'Aligent Consulting',
    private: true,
    license: 'MIT',
    type: 'module',
    scripts: {
        test: 'nx affected -t test --coverage',
        'test:all': 'nx run-many -t test --coverage',
        lint: 'nx affected -t lint',
        'lint:all': 'nx run-many -t lint',
        typecheck: 'nx affected -t typecheck',
        'typecheck:all': 'nx run-many -t typecheck',
        postinstall: `[ -d .git ] && git config core.hooksPath '.git-hooks' && chmod +x .git-hooks/* || true`,
        'pg:synth': `nx run application:cdk synth 'development/**' --exclusively --profile playground`,
        'pg:deploy': `nx run application:cdk deploy --method 'direct' 'development/**' --exclusively --require-approval never --profile playground`,
        'pg:destroy': "nx run application:cdk destroy 'development/**' --profile playground",
        audit: 'nx run-many -t lint typecheck test --configuration coverage --skip-nx-cache',
    },
    dependencies: {
        '@aligent/microservice-util-lib': '^1.2.0',
    },
    devDependencies: {
        '@aligent/cdk-step-function-from-file': '^0.3.2',
        '@aligent/nx-openapi': '^1.0.0',
        '@aligent/ts-code-standards': '^4.1.0',
        '@nx/eslint': '22.1.3',
        '@nx/eslint-plugin': '22.1.3',
        '@nx/js': '22.1.3',
        '@nx/vite': '22.1.3',
        '@swc-node/register': '^1.10.10',
        '@swc/core': '^1.13.3',
        '@swc/helpers': '^0.5.17',
        '@types/aws-lambda': '^8.10.152',
        '@types/node': '^22.17.0',
        '@typescript-eslint/eslint-plugin': '8.44.0',
        '@typescript-eslint/parser': '8.44.0',
        '@vitest/coverage-v8': '^3.2.4',
        '@vitest/ui': '^3.2.4',
        'aws-cdk': '^2.1033.0',
        'aws-cdk-lib': '^2.230.0',
        'cdk-nag': '^2.37.55',
        constructs: '^10.4.3',
        eslint: '^9.32.0',
        'eslint-config-prettier': '^10.1.8',
        'eslint-plugin-import': '^2.32.0',
        'fast-glob': '^3.3.3',
        jiti: '2.5.1',
        'jsonc-eslint-parser': '^2.4.0',
        nx: '22.1.3',
        prettier: '^3.6.2',
        // FIXME: [MI-251] Rolldown is still in beta. We pin the version and can upgrade with precaution.
        rolldown: '1.0.0-beta.53',
        'store-parameters': '^1.1.3',
        tslib: '^2.8.1',
        tsx: '^4.21.0',
        typescript: '~5.9.2',
        vite: '^7.2.6',
        vitest: '^3.2.4',
    },
    workspaces: ['application', 'clients', 'libs/*', 'services/*'],
    packageManager:
        'yarn@4.12.0+sha512.f45ab632439a67f8bc759bf32ead036a1f413287b9042726b7cc4818b7b49e14e9423ba49b18f9e06ea4941c1ad062385b1d8760a8d5091a1a31e5f6219afca8',
} as const;
