export const PACKAGE_JSON = {
    author: 'Aligent Consulting',
    private: true,
    license: 'MIT',
    type: 'module',
    scripts: {
        test: 'nx affected -t test --coverage',
        'test:all': 'nx run-many -t test --coverage',
        lint: 'nx affected -t lint',
        'lint:all': 'nx run-many -t lint',
        typecheck: 'nx affected -t typecheck',
        'typecheck:all': 'nx run-many -t typecheck',
        postinstall: `[ -d .git ] && git config core.hooksPath '.git-hooks' || true`,
        'pg:synth': `nx run application:cdk synth 'dev/**' --exclusively --profile playground`,
        'pg:deploy': `nx run application:cdk deploy --method 'direct' 'dev/**' --exclusively --require-approval never --profile playground`,
        'pg:destroy': "nx run application:cdk destroy 'dev/**' --profile playground",
        audit: 'nx run-many -t lint typecheck test --configuration coverage --skip-nx-cache',
    },
    dependencies: {},
    devDependencies: {
        '@aligent/step-function-from-file': '^0.3.2',
        '@aligent/ts-code-standards': '^4.1.0',
        '@nx/eslint': '21.5.2',
        '@nx/eslint-plugin': '21.5.2',
        // '@nx/js': '21.5.2', // TODO double check if it's actually needed
        '@nx/rsbuild': '21.5.2',
        '@nx/vite': '21.5.2',
        '@rsbuild/core': '^1.5.6',
        '@swc-node/register': '^1.10.10',
        '@swc/core': '^1.13.3',
        '@swc/helpers': '^0.5.17',
        '@types/aws-lambda': '^8.10.152',
        '@types/node': '^22.17.0',
        '@typescript-eslint/eslint-plugin': '8.44.0',
        '@typescript-eslint/parser': '8.44.0',
        '@vitest/coverage-v8': '^3.2.4',
        '@vitest/ui': '^3.2.4',
        'aws-cdk': '^2.1033.0',
        'aws-cdk-lib': '^2.230.0',
        'cdk-nag': '^2.37.55',
        constructs: '^10.4.3',
        esbuild: '~0.25.8', // TODO Do we need this package now that we're using rsbuild instead
        'esbuild-visualizer': '^0.7.0',
        eslint: '^9.32.0',
        'eslint-config-prettier': '^10.1.8',
        'eslint-plugin-import': '^2.32.0',
        'fast-glob': '^3.3.3',
        jiti: '2.5.1',
        'jsonc-eslint-parser': '^2.4.0',
        nx: '21.5.2',
        // open: '^10.2.0', // TODO Double check what is this and why it's here?
        prettier: '^3.6.2',
        'store-parameters': '^1.0.6',
        tslib: '^2.8.1',
        typescript: '~5.9.2',
        vite: '7.1.6',
        vitest: '^3.2.4',
    },
    workspaces: ['libs/*', 'services/*', 'application/*'],
    packageManager:
        'yarn@4.9.2+sha512.1fc009bc09d13cfd0e19efa44cbfc2b9cf6ca61482725eb35bbc5e257e093ebf4130db6dfe15d604ff4b79efd8e1e8e99b25fa7d0a6197c9f9826358d4d65c3c',
} as const;
