name: CI

on:
  pull_request:
    branches:
      - '**' # Trigger on all branches

permissions:
  actions: read
  contents: read

jobs:
  code-quality:
    name: 🕵️‍♀️ Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Fetch target
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}
        run: git fetch origin ${{ env.BASE_REF }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@dbe0650947e5f2c81f59190a38512cf49126fe6b # v4

      - name: Check for version plan
        run: npx nx release plan:check --verbose

      - name: ⚙️ Run Tests
        run: npx nx affected -t lint test --parallel=2

      - name: ⚙️ Run Build
        run: npx nx affected -t build
