name: Pull request check

on: [pull_request]

permissions:
  actions: read
  contents: write

jobs:
  code-quality:
    name: 🕵️‍♀️ Code Quality Check
    if: ${{ !startsWith(github.head_ref, 'release-pr/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Fetch target
        run: git fetch origin ${{ env.BASE_REF }}
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
          package-manager-cache: false

      - name: Enable Corepack
        run: corepack enable

      - name: Configure Dependency Cache
        uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@afb73a62d26e41464e9254689e1fd6122ee683c1 # v5

      - name: 🧪 Run Lint, Type Check & Tests
        run: yarn nx affected -t typecheck lint test --parallel=3

      - name: ⚙️ Run Build
        run: yarn nx affected -t build

      - name: ⚙️ Run release plan check
        run: yarn nx release plan:check --verbose
