name: Publish to NPM

on: workflow_dispatch

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Fetch target
        run: git fetch origin ${{ env.BASE_REF }}
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}

      - name: Config git user
        run: |
          git config --global user.name "Automated NPM Release"
          git config --global user.email "${{ secrets.DEVOPS_GITHUB_EMAIL }}"

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci
        shell: bash

      - name: Release new package versions
        run: npx nx release --dry-run
        shell: bash

      - name: Publish to NPM
        run: npx nx release publish --dry-run
        shell: bash
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Push version changes
        run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
