name: Publish to NPM

on:
  # Run manually using Github UI
  workflow_dispatch:
    inputs:
      publish-flags:
        description: 'Additional flags to pass to publish command'
        required: false
        default: ''

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Fetch target
        run: git fetch origin ${{ env.BASE_REF }}
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}

      - name: Config git user
        run: |
          git config --global user.name "Automated NPM Release"
          git config --global user.email "${{ secrets.DEVOPS_GITHUB_EMAIL }}"

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci
        shell: bash

      - name: Check for version plan
        run: npx nx release plan:check --verbose
        shell: bash

      - name: Release new version plan
        run: npx nx release --verbose
        shell: bash

      - name: Publish packages
        run: npx nx release publish --verbose ${{ inputs.publish-flags }}
        shell: bash
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Push version changes
        run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
