name: Release new version

on:
  push:
    branches:
      - 'release/*'  # This matches any branch starting with 'release/'

jobs:
  release:
    name: Release new version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Fetch target
        run: git fetch origin ${{ env.BASE_REF }}
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}

      - name: Config git user
        run: |
          git config --global user.name "Automated NPM Release"
          git config --global user.email "kai.nguyen@aligent.com.au"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci
        shell: bash

      - name: Check for version plan
        run: npx nx release plan:check --verbose
        shell: bash

      - name: Release new version
        run: npx nx release --skip-publish --verbose
        shell: bash

      # - name: Push version changes
      #   run: git push && git push --tags
      #   env:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
